#Configuración del ticket de venta
#Mon Mar 09 00:30:33 CST 2026
cedula=
dato_opcional_1=
dato_opcional_2=
direccion=
nombre_negocio=VERDULERIA VL
pie=Gracias por su compra\!
subtitulo=SellControl POS
telefono=
